# Generated by Django 6.0.4 on 2026-05-03 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=20)),
                ('colegiado', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='medicamentos')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField()),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('instrucciones', models.TextField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.medicamento')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_toma', models.DateField()),
                ('is_tomado', models.BooleanField(default=False)),
                ('hora', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.paciente')),
                ('tratamiento_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinix.tratamientomedicamento')),
            ],
        ),
    ]
