# Generated by Django 6.0.4 on 2026-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
