# Generated by Django 6.0.4 on 2026-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0002_medicamento_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos'),
        ),
    ]
