# Generated by Django 6.0.4 on 2026-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0003_alter_medicamento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromedication',
            name='is_tomado',
        ),
        migrations.AddField(
            model_name='registromedication',
            name='estado',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
