# Generated by Django 6.0.4 on 2026-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0004_remove_registromedication_is_tomado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientomedicamento',
            name='frecuencia',
            field=models.CharField(default='Diario', max_length=30),
        ),
    ]
