# Generated by Django 6.0.4 on 2026-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0005_add_frecuencia_to_tratamientomedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedication',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='registro_medicacion'),
        ),
        migrations.AddField(
            model_name='registromedication',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
