# Generated by Django 6.0.4 on 2026-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0006_add_foto_observaciones_to_registromedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
