# Generated by Django 6.0.4 on 2026-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0006_add_foto_observaciones_to_registromedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
